apiVersion: apps/v1
kind: Deployment
metadata:
  name: faucet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faucet
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: faucet
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: "secrets-init"
          image: doitintl/secrets-init:0.2.12
          command:
            - sh
          args:
            - -c
            - "cp /usr/local/bin/secrets-init /secrets-init/bin/secrets-init"
          volumeMounts:
          - mountPath: /secrets-init/bin
            name: "secrets-init-volume"
      serviceAccountName: {{ .Values.google_sa_name }}
      containers:
        - name: faucet
          image: {{ index .Values.werf.image "faucet" }}
          env:
            - name: DATABASE_URL
              value: gcp:secretmanager:projects/{{ .Values.google_project_id }}/secrets/FAUCET_DATABASE_URI
            - name: PRIVATE_KEY
              value: gcp:secretmanager:projects/{{ .Values.google_project_id }}/secrets/FAUCET_PRIVATE_KEY
            - name: PORT
              value: 8080
            - name: WEB3_PROVIDER
              value: {{ .Values.ethereum_jsonrpc_http_url }}
          command:
            - "/secrets-init/bin/secrets-init"
          args:
            - "--provider"
            - "/entrypoint.sh"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - mountPath: /secrets-init/bin
              name: "secrets-init-volume"
      volumes:
        - name: "secrets-init-volume"
          emptyDir: {}
