---

apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: faucet-cert
spec:
  domains:
    - testedge.haqq.network

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faucet-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: faucet-address
    networking.gke.io/managed-certificates: faucet-cert
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: faucet-svc
      port:
        number: 8080

---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: faucet-backendconfig
spec:
  securityPolicy:
    name: "policy"

---

apiVersion: v1
kind: Service
metadata:
  name: faucet-svc
  labels:
    app: faucet
  annotations:
    cloud.google.com/backend-config: '{"default": "faucet-backendconfig"}'
spec:
  type: "NodePort"
  selector:
    app: faucet
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
